import { invoke } from '@tauri-apps/api/core'
import { Copy, Eye, EyeSlash } from '@phosphor-icons/react'
import { useCallback, useEffect, useState } from 'react'
import type { createTranslator } from '../lib/i18n'
import { trackBridgeTokenCopied } from '../lib/productAnalytics'
import { isTauri } from '../mock-tauri'
import type { Settings } from '../types'
import { writeClipboardText } from '../utils/clipboardText'
import { Button } from './ui/button'

type Translate = ReturnType<typeof createTranslator>

type CopyStatus = 'idle' | 'copied' | 'failed'

/** Fixed-width stand-in so the mask never leaks the token's real length. */
const MASK = '•'.repeat(32)

/**
 * Shows the shared secret a browser extension needs to reach the MCP tool
 * bridge (ADR-0159), masked until the user asks to see it.
 *
 * Reads the token itself rather than taking it as a prop: it is generated by
 * Rust, never edited here, and never part of the Settings save draft, so
 * threading it through the settings-draft plumbing would misrepresent it as
 * an editable preference.
 *
 * Renders nothing when there is no token — a bridge with no token refuses
 * every extension anyway, so an empty field would be an invitation to pair
 * something that cannot work.
 */
export function BridgeTokenRow({ t }: { t: Translate }) {
  const [token, setToken] = useState<string | null>(null)
  const [revealed, setRevealed] = useState(false)
  const [status, setStatus] = useState<CopyStatus>('idle')

  useEffect(() => {
    // The token only means anything to the desktop app that spawned the
    // bridge. Outside Tauri there is nothing to pair, and asking would only
    // produce a rejected call to warn about.
    if (!isTauri()) return undefined

    let cancelled = false
    invoke<Settings>('get_settings', {})
      .then((settings) => {
        if (!cancelled) setToken(settings?.bridge_token?.trim() || null)
      })
      .catch((error) => {
        console.warn('Failed to read the bridge token:', error)
      })
    return () => {
      cancelled = true
    }
  }, [])

  const copy = useCallback(async () => {
    if (!token) return
    try {
      await writeClipboardText(token)
      setStatus('copied')
      trackBridgeTokenCopied()
    } catch (error) {
      console.warn('Failed to copy the bridge token:', error)
      setStatus('failed')
    }
  }, [token])

  if (!token) return null

  return (
    <div className="rounded-md border border-border bg-card p-3" data-testid="bridge-token-row">
      <div className="text-sm font-medium text-foreground">{t('settings.bridgeToken.title')}</div>
      <p className="mt-1 text-xs text-muted-foreground">
        {t('settings.bridgeToken.description')}
      </p>
      <div className="mt-2 flex items-center gap-2">
        <code
          className="flex-1 truncate rounded border border-border bg-background px-2 py-1 font-mono text-xs"
          data-testid="bridge-token-value"
        >
          {revealed ? token : MASK}
        </code>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => setRevealed((value) => !value)}
          aria-label={revealed ? t('settings.bridgeToken.hide') : t('settings.bridgeToken.reveal')}
          data-testid="bridge-token-reveal"
        >
          {revealed ? <EyeSlash size={15} /> : <Eye size={15} />}
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={copy}
          aria-label={t('settings.bridgeToken.copy')}
          data-testid="bridge-token-copy"
        >
          <Copy size={15} />
        </Button>
      </div>
      {status === 'idle' ? null : (
        <p
          className="mt-2 text-xs text-muted-foreground"
          role="status"
          data-testid="bridge-token-status"
        >
          {status === 'copied'
            ? t('settings.bridgeToken.copied')
            : t('settings.bridgeToken.copyFailed')}
        </p>
      )}
    </div>
  )
}
