import { createRef } from 'react'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { ConnectionsPanel, type ConnectionsPanelHandle } from './ConnectionsPanel'
import type { SessionActivityRetainedState } from './SessionActivityHistory'
vi.mock('./graph/GraphView', () => ({ default: ({ onOpenNote }: { onOpenNote?: (path: string) => void }) => <button type="button" onClick={() => onOpenNote?.('/vault/graph.md')}>Graph canvas</button> }))
vi.mock('./SessionActivityHistory', () => ({ SessionActivityHistory: ({ onOpenNote, retainedState }: { onOpenNote?: (path: string) => void, retainedState?: SessionActivityRetainedState }) => <button type="button" data-testid="mock-session-activity" data-focused-path={retainedState?.path || ''} onClick={() => onOpenNote?.('/vault/activity.md')}>Recorded actions</button> }))
beforeEach(() => localStorage.clear())
it('shows one view at a time and can expand and collapse it', async () => {
  render(<ConnectionsPanel vaultPath="/vault" />)
  fireEvent.click(screen.getByTestId('connections-edge'))
  expect(await screen.findByText('Graph canvas')).toBeVisible()
  fireEvent.click(screen.getByRole('tab', { name: 'Mycelium' }))
  expect(await screen.findByText('Recorded actions')).toBeVisible()
  expect(screen.queryByText('Graph canvas')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Expand connections' }))
  expect(screen.getByTestId('connections-panel')).toHaveAttribute('data-expanded', 'true')
  fireEvent.click(screen.getByRole('button', { name: 'Return to side panel' }))
  expect(screen.getByTestId('connections-panel')).toHaveAttribute('data-expanded', 'false')
})
it('tears down the inactive renderer when switching views', async () => {
  render(<ConnectionsPanel vaultPath="/vault" />)
  fireEvent.click(screen.getByTestId('connections-edge'))
  expect(await screen.findByText('Graph canvas')).toBeVisible()
  fireEvent.click(screen.getByRole('tab', { name: 'Mycelium' }))
  expect(await screen.findByText('Recorded actions')).toBeVisible()
  expect(screen.queryByText('Graph canvas')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('tab', { name: 'Graph' }))
  expect(await screen.findByText('Graph canvas')).toBeVisible()
  expect(screen.queryByText('Recorded actions')).not.toBeInTheDocument()
})
it('leaves the expanded overlay when either view opens a note', async () => {
  const open = vi.fn()
  render(<ConnectionsPanel vaultPath="/vault" onOpenNote={open} />)
  fireEvent.click(screen.getByTestId('connections-edge'))
  fireEvent.click(screen.getByRole('tab', { name: 'Mycelium' }))
  fireEvent.click(await screen.findByRole('button', { name: 'Expand connections' }))
  fireEvent.click(await screen.findByText('Recorded actions'))
  expect(open).toHaveBeenCalledWith('/vault/activity.md')
  expect(screen.queryByTestId('connections-panel')).not.toBeInTheDocument()
})
it('opens a requested view through the imperative handle, from the closed edge', async () => {
  const ref = createRef<ConnectionsPanelHandle>()
  render(<ConnectionsPanel ref={ref} vaultPath="/vault" />)
  expect(screen.getByTestId('connections-edge')).toBeInTheDocument()
  ref.current?.openView('graph')
  expect(await screen.findByText('Graph canvas')).toBeVisible()
})
it('focuses a specific Mycelium session when a caller requests it', async () => {
  const ref = createRef<ConnectionsPanelHandle>()
  render(<ConnectionsPanel ref={ref} vaultPath="/vault" />)
  ref.current?.openView('mycelium', { focusPath: '/prime/sessions/abc.jsonl' })
  expect(await screen.findByTestId('mock-session-activity')).toHaveAttribute('data-focused-path', '/prime/sessions/abc.jsonl')
})
it('re-focuses Mycelium to a new session on a second request', async () => {
  const ref = createRef<ConnectionsPanelHandle>()
  render(<ConnectionsPanel ref={ref} vaultPath="/vault" />)
  ref.current?.openView('mycelium', { focusPath: '/prime/sessions/first.jsonl' })
  expect(await screen.findByTestId('mock-session-activity')).toHaveAttribute('data-focused-path', '/prime/sessions/first.jsonl')
  ref.current?.openView('mycelium', { focusPath: '/prime/sessions/second.jsonl' })
  await waitFor(() => expect(screen.getByTestId('mock-session-activity')).toHaveAttribute('data-focused-path', '/prime/sessions/second.jsonl'))
})
it('persists independent view preferences and retains a way to re-enable views', () => {
  const first = render(<ConnectionsPanel vaultPath="/vault" />)
  fireEvent.click(screen.getByTestId('connections-edge'))
  fireEvent.click(screen.getByText('Connections settings'))
  fireEvent.change(screen.getByLabelText('Graph placement'), { target: { value: 'off' } })
  fireEvent.change(screen.getByLabelText('Mycelium placement'), { target: { value: 'off' } })
  first.unmount()
  render(<ConnectionsPanel vaultPath="/vault" />)
  fireEvent.click(screen.getByTestId('connections-edge'))
  expect(screen.getByText('Enable a view in Connections settings.')).toBeVisible()
  expect(screen.queryByRole('tab')).not.toBeInTheDocument()
})
