//! First-run starter content for a brand-new destination vault (Phase 3.3,
//! `docs/plans/...`). Before this, a fresh `agent_memory_vault_path` was a
//! totally blank folder — nothing demonstrated what a filled-in Rhizome
//! wiki looks like. Seeds once, only into a genuinely empty directory, so
//! it never touches an existing personal vault the user pointed the
//! Research panel at.

use std::fs;
use std::path::Path;

use crate::rhizome_write_location::{
    default_frontmatter, is_wiki_vault, resolve_write_path, ArtifactKind,
};

const RHIZOME_VAULT_MARKER: &str = "# Rhizome Vault\n\n\
This folder is a Rhizome wiki vault — a knowledge graph built by the \
Research panel's Generate, Import, and Distill tools. Pages here are \
linked with `[[wikilinks]]`; use search (⌘K) to jump between them.\n";

const EXAMPLE_CONCEPT_TITLE: &str = "Rhizome (concept)";
const EXAMPLE_CONCEPT_BODY: &str = "\
A rhizome is a botanical structure that spreads horizontally underground, \
sending up new shoots at intervals rather than growing from a single root. \
This vault borrows the metaphor: knowledge here grows the same way — every \
[[example-entity|note]] can link to others, and the graph as a whole \
matters more than any single starting point.\n\n\
Generated by [[example-source|Rhizome's Research panel]] as example \
starter content.\n";

const EXAMPLE_ENTITY_TITLE: &str = "Example Entity";
const EXAMPLE_ENTITY_BODY: &str = "\
A stand-in for whatever this vault will actually track — a person, a \
project, a codebase. Real entities show up here once you run Generate, \
Import, or Distill on something real.\n\n\
See also: [[rhizome-concept|the rhizome concept]] this vault is named for.\n";

const EXAMPLE_SOURCE_TITLE: &str = "Example Source";
const EXAMPLE_SOURCE_BODY: &str = "\
Source pages like this one record where a piece of knowledge came from — \
a repo, a document, a research session. Delete these three example pages \
whenever you're ready; they're only here to show the shape of a filled-in \
vault before you've run your first real Generate/Import/Distill.\n";

/// True when `vault_path` has no visible entries — the only case it's safe
/// to auto-seed into. A personal notes vault that merely lacks the
/// `RHIZOME_VAULT.md` marker (because it isn't dedicated to Rhizome) must
/// never get example content injected into it.
fn is_empty_directory(vault_path: &Path) -> bool {
    let Ok(mut entries) = fs::read_dir(vault_path) else {
        return false;
    };
    entries.all(|entry| {
        entry
            .ok()
            .map(|e| e.file_name().to_string_lossy().starts_with('.'))
            .unwrap_or(true)
    })
}

fn write_page(
    vault_path: &Path,
    kind: ArtifactKind,
    slug: &str,
    title: &str,
    body: &str,
    now: &str,
) -> Result<(), String> {
    let path = resolve_write_path(vault_path, kind, slug);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create dir: {e}"))?;
    }
    let frontmatter = default_frontmatter(kind, title, now);
    fs::write(&path, format!("{frontmatter}\n# {title}\n\n{body}"))
        .map_err(|e| format!("Failed to write {}: {e}", path.display()))
}

/// Seed example content into `vault_path` if — and only if — it's an
/// empty, unmarked directory. Idempotent: a no-op once the vault has any
/// content or is already marked as a Rhizome vault. Called from the entry
/// of each research write verb so it fires transparently on first use,
/// with no dedicated "create a vault" UI needed.
pub fn seed_if_empty(vault_path: &Path, now: &str) -> Result<(), String> {
    if is_wiki_vault(vault_path) || !is_empty_directory(vault_path) {
        return Ok(());
    }

    // Nested wiki/ layout wins for genuinely new vaults (vault_uses_flat_layout
    // only activates when a wiki/ dir is absent AND a legacy marker is
    // present) — create it before the marker so seeded pages land nested.
    fs::create_dir_all(vault_path.join("wiki"))
        .map_err(|e| format!("Failed to create dir: {e}"))?;
    fs::write(vault_path.join("RHIZOME_VAULT.md"), RHIZOME_VAULT_MARKER)
        .map_err(|e| format!("Failed to write RHIZOME_VAULT.md: {e}"))?;

    write_page(
        vault_path,
        ArtifactKind::Concept,
        "rhizome-concept",
        EXAMPLE_CONCEPT_TITLE,
        EXAMPLE_CONCEPT_BODY,
        now,
    )?;
    write_page(
        vault_path,
        ArtifactKind::Entity,
        "example-entity",
        EXAMPLE_ENTITY_TITLE,
        EXAMPLE_ENTITY_BODY,
        now,
    )?;
    write_page(
        vault_path,
        ArtifactKind::Document,
        "example-source",
        EXAMPLE_SOURCE_TITLE,
        EXAMPLE_SOURCE_BODY,
        now,
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn seeds_marker_and_three_pages_into_an_empty_vault() {
        let dir = TempDir::new().unwrap();

        seed_if_empty(dir.path(), "2026-07-12T00:00:00Z").unwrap();

        assert!(dir.path().join("RHIZOME_VAULT.md").is_file());
        assert!(dir
            .path()
            .join("wiki/concepts/rhizome-concept.md")
            .is_file());
        assert!(dir.path().join("wiki/entities/example-entity.md").is_file());
        assert!(dir
            .path()
            .join("wiki/sources/documents/example-source.md")
            .is_file());
    }

    #[test]
    fn seeded_pages_wikilink_each_other() {
        let dir = TempDir::new().unwrap();
        seed_if_empty(dir.path(), "now").unwrap();

        let concept =
            fs::read_to_string(dir.path().join("wiki/concepts/rhizome-concept.md")).unwrap();
        assert!(concept.contains("[[example-entity"));

        let entity =
            fs::read_to_string(dir.path().join("wiki/entities/example-entity.md")).unwrap();
        assert!(entity.contains("[[rhizome-concept"));
    }

    #[test]
    fn does_not_seed_a_non_empty_directory() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("my-real-note.md"), "# Real note\n").unwrap();

        seed_if_empty(dir.path(), "now").unwrap();

        assert!(!dir.path().join("RHIZOME_VAULT.md").exists());
        assert!(!dir.path().join("wiki").exists());
    }

    #[test]
    fn does_not_reseed_an_already_marked_vault() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("RHIZOME_VAULT.md"),
            "# Rhizome Vault\ncustom content\n",
        )
        .unwrap();

        seed_if_empty(dir.path(), "now").unwrap();

        // Untouched — no wiki/ dir created, marker content unchanged.
        assert!(!dir.path().join("wiki").exists());
        let marker = fs::read_to_string(dir.path().join("RHIZOME_VAULT.md")).unwrap();
        assert_eq!(marker, "# Rhizome Vault\ncustom content\n");
    }

    #[test]
    fn treats_a_directory_with_only_dotfiles_as_empty() {
        let dir = TempDir::new().unwrap();
        fs::create_dir_all(dir.path().join(".git")).unwrap();
        fs::write(dir.path().join(".gitignore"), "").unwrap();

        seed_if_empty(dir.path(), "now").unwrap();

        assert!(dir.path().join("RHIZOME_VAULT.md").is_file());
    }

    #[test]
    fn is_idempotent_on_repeated_calls() {
        let dir = TempDir::new().unwrap();
        seed_if_empty(dir.path(), "now").unwrap();
        let first = fs::read_to_string(dir.path().join("RHIZOME_VAULT.md")).unwrap();

        // A second call must not error or duplicate/overwrite content —
        // the vault is now marked, so it's a no-op.
        seed_if_empty(dir.path(), "later").unwrap();
        let second = fs::read_to_string(dir.path().join("RHIZOME_VAULT.md")).unwrap();
        assert_eq!(first, second);
    }
}
